#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

SERVICE_FRAGMENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_DIR="${LITELLM_MENU_SCRIPT_DIR:-$(cd "$SERVICE_FRAGMENT_DIR/.." && pwd)}"

if [[ "$SCRIPT_DIR" != */Contents/Resources/App \
  && "${LITELLM_ALLOW_CHECKOUT_SERVICE:-0}" != "1" ]]; then
  APP_CONTROL="${LITELLM_APP_SERVICE_SCRIPT:-/Applications/LiteLLM Menu.app/Contents/Resources/App/service.sh}"
  if [[ -x "$APP_CONTROL" && "$(cd "$(dirname "$APP_CONTROL")" && pwd)" != "$SCRIPT_DIR" ]]; then
    APP_CONTROL_DIR="$(cd "$(dirname "$APP_CONTROL")" && pwd)"
    exec env \
      LITELLM_TEMPLATE_ROOT="$APP_CONTROL_DIR" \
      "$APP_CONTROL" "$@"
  fi
fi

DEFAULT_RUNTIME_ROOT="${LITELLM_MENU_HOME:-$HOME/.litellm-menu}"
DEFAULT_ROOT="$DEFAULT_RUNTIME_ROOT"

ROOT="${LITELLM_RUNTIME_ROOT:-$DEFAULT_ROOT}"
TEMPLATE_ROOT="${LITELLM_TEMPLATE_ROOT:-$SCRIPT_DIR}"
export PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"
RUNTIME_SETTINGS_FILE="${LITELLM_MENU_RUNTIME_SETTINGS_FILE:-$ROOT/runtime-settings.env}"
RUNTIME_SETTINGS_RETAIN_EXISTING_VALUE="__LITELLM_MENU_RETAIN_EXISTING__"

runtime_settings_key_accepts_value() {
  case "$1" in
    LITELLM_MENU_LOG_MAX_BYTES|\
    LITELLM_PORT|\
    LITELLM_MENU_DEPLOYMENT_COOLDOWN_FAILURES|\
    LITELLM_MENU_IMAGE_TOOL_FALLBACK_MAX_ATTEMPTS|\
    LITELLM_MENU_WEB_SEARCH_MAX_RESULTS|\
    LITELLM_MENU_WEB_SEARCH_READ_RESULTS|\
    LITELLM_MENU_WEB_SEARCH_READ_CHARS|\
    LITELLM_MENU_WEB_SEARCH_MAX_ROUNDS|\
    LITELLM_MENU_WEB_SEARCH_MAX_QUERIES|\
    LITELLM_MENU_WEB_SEARCH_MAX_OPEN_PAGES|\
    LITELLM_MENU_WEB_SEARCH_MAX_FIND_IN_PAGE|\
    LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRIES|\
    LITELLM_MENU_ROUTE_TRACE_PREVIEW_CHARS|\
    LITELLM_NUM_WORKERS|\
    LITELLM_MAX_REQUESTS_BEFORE_RESTART|\
    LITELLM_STATE_TTL_SECONDS|\
    LITELLM_HEALTH_WAIT_SECONDS|\
    LITELLM_RUNTIME_VERIFY_WAIT_SECONDS|\
    LITELLM_SERVICE_LIFECYCLE_LOCK_WAIT_SECONDS|\
    LITELLM_SERVICE_THROTTLE_INTERVAL_SECONDS|\
    LITELLM_MENU_COMPUTER_FACADE_MAX_STEPS)
      [[ "$2" =~ ^[0-9]+$ ]]
      return
      ;;
    LITELLM_MENU_REQUEST_TIMEOUT_SECONDS|\
    LITELLM_MENU_STALL_TIMEOUT_SECONDS|\
    LITELLM_MENU_STREAM_START_TIMEOUT_SECONDS|\
    LITELLM_MENU_CODEX_COMPACTION_START_TIMEOUT_SECONDS|\
    LITELLM_MENU_RECOVERY_MAX_SECONDS|\
    LITELLM_MENU_RECOVERY_INTERVAL_SECONDS|\
    LITELLM_MENU_WEB_FETCH_TIMEOUT_SECONDS|\
    LITELLM_MENU_DEPLOYMENT_COOLDOWN_SECONDS|\
    LITELLM_MENU_VISION_BRIDGE_TIMEOUT_SECONDS|\
    LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRY_DELAY_SECONDS|\
    LITELLM_CONFIG_WATCH_INTERVAL|\
    LITELLM_CONFIG_WATCH_SETTLE_INTERVAL|\
    LITELLM_WEBDAV_TIMEOUT)
      [[ "$2" =~ ^[0-9]+([.][0-9]+)?$ ]]
      return
      ;;
    LITELLM_MENU_COMPUTER_FACADE_TRACE|\
    LITELLM_MENU_COMPUTER_FACADE_TRACE_SCREENSHOTS|\
    LITELLM_MENU_COMPUTER_FACADE_REQUIRE_OBSERVATION|\
    LITELLM_USE_SYSTEM_PROXIES)
      [[ "$2" =~ ^(0|1|true|false|yes|no|on|off)$ ]]
      return
      ;;
    LITELLM_MENU_COMPUTER_FACADE_BACKEND)
      [[ "$2" =~ ^(auto|mcp|browser|chrome|playwright|cua|mock)$ ]]
      return
      ;;
    LITELLM_MENU_VISION_BRIDGE_BACKEND)
      [[ "$2" =~ ^(auto|api|local|off)$ ]]
      return
      ;;
    LITELLM_MENU_VISION_BRIDGE_MODE)
      [[ "$2" =~ ^(0|1|true|false|yes|no|on|off|auto|enabled|disabled)$ ]]
      return
      ;;
    LITELLM_MENU_COMPUTER_FACADE_MODEL|\
    LITELLM_MENU_COMPUTER_FACADE_ACTION_DENYLIST|\
    LITELLM_MENU_VISION_BRIDGE_API_BASE|\
    LITELLM_MENU_VISION_BRIDGE_MODEL|\
    LITELLM_MENU_VISION_BRIDGE_PROMPT)
      [[ "$2" != *$'\n'* && "$2" != *$'\r'* && "$2" != *'#'* ]]
      return
      ;;
    LITELLM_MENU_VISION_BRIDGE_API_KEY)
      [[ -n "$2" \
        && "$2" != "$RUNTIME_SETTINGS_RETAIN_EXISTING_VALUE" \
        && "$2" != *$'\n'* \
        && "$2" != *$'\r'* \
        && "$2" != *'#'* ]]
      return
      ;;
    LITELLM_MENU_WEB_SEARCH_DDGS_BACKEND)
      [[ -n "$2" && "$2" != *$'\n'* && "$2" != *$'\r'* && "$2" != *'#'* ]]
      return
      ;;
    LITELLM_MENU_WEB_SEARCH_REGION)
      [[ -n "$2" && "$2" != *[[:space:]]* && "$2" != *'#'* ]]
      return
      ;;
    LITELLM_MENU_VISION_BRIDGE_LOCAL_FORMAT)
      [[ "$2" =~ ^(compact|detailed)$ ]]
      return
      ;;
    *)
      return 1
      ;;
  esac
}

load_runtime_settings_file() {
  [[ -f "$RUNTIME_SETTINGS_FILE" ]] || return 0
  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" == *=* ]] || continue
    key="${line%%=*}"
    value="${line#*=}"
    key="${key//[[:space:]]/}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    runtime_settings_key_accepts_value "$key" "$value" || continue
    export "$key=$value"
  done < "$RUNTIME_SETTINGS_FILE"
}

load_runtime_settings_file

if [[ -z "${LITELLM_MENU_VISION_BRIDGE_BACKEND:-}" && -n "${LITELLM_MENU_VISION_BRIDGE_MODE:-}" ]]; then
  vision_bridge_mode_compat="$(printf '%s' "$LITELLM_MENU_VISION_BRIDGE_MODE" | tr '[:upper:]' '[:lower:]')"
  case "$vision_bridge_mode_compat" in
    0|false|no|off|disabled)
      export LITELLM_MENU_VISION_BRIDGE_BACKEND="off"
      ;;
    1|true|yes|on|auto|enabled)
      export LITELLM_MENU_VISION_BRIDGE_BACKEND="auto"
      ;;
  esac
  unset vision_bridge_mode_compat
fi

DEFAULT_CONFIG_FILE="$ROOT/config.yaml"
MIRROR_CHECKOUT_CONFIG_TO_ROOT=0
if [[ -z "${LITELLM_CONFIG_FILE:-}" \
  && -z "${LITELLM_RUNTIME_ROOT:-}" \
  && -z "${LITELLM_MENU_HOME:-}" \
  && "$SCRIPT_DIR" != */Contents/Resources/App \
  && -f "$SCRIPT_DIR/config.yaml" ]]; then
  DEFAULT_CONFIG_FILE="$SCRIPT_DIR/config.yaml"
  MIRROR_CHECKOUT_CONFIG_TO_ROOT=1
fi
CONFIG_FILE="${LITELLM_CONFIG_FILE:-$DEFAULT_CONFIG_FILE}"
RUNTIME_DIR="${LITELLM_RUNTIME_DIR:-$ROOT/.litellm-runtime}"
RUNTIME_CONFIG="${LITELLM_RUNTIME_CONFIG:-$RUNTIME_DIR/config.yaml}"
RUNTIME_RELOAD_FINGERPRINT="${LITELLM_RUNTIME_RELOAD_FINGERPRINT:-$RUNTIME_DIR/reload-fingerprint.json}"
DEPLOYMENT_COOLDOWN_FILE="${LITELLM_MENU_DEPLOYMENT_COOLDOWN_FILE:-$RUNTIME_DIR/deployment-cooldowns.json}"
ROUTE_RECOVERY_STATE_FILE="${LITELLM_MENU_ROUTE_RECOVERY_STATE_FILE:-$RUNTIME_DIR/route-recovery-state.json}"
CALLBACK_SOURCE="$TEMPLATE_ROOT/litellm_menu/callbacks.py"
CALLBACK_PACKAGE_DIR="$TEMPLATE_ROOT/litellm_menu"
LOG_FILE="${LITELLM_MENU_LOG:-$ROOT/menu-server.log}"
MENU_ACTIONS_LOG="${LITELLM_MENU_ACTIONS_LOG:-$ROOT/menu-actions.log}"
RECENT_REQUESTS_LOG="${LITELLM_RECENT_REQUESTS_LOG:-$ROOT/recent-requests.jsonl}"
LOCAL_LOG_MAX_BYTES="${LITELLM_MENU_LOG_MAX_BYTES:-10485760}"
REQUEST_TIMEOUT_SECONDS="${LITELLM_MENU_REQUEST_TIMEOUT_SECONDS:-7200}"
STALL_TIMEOUT_SECONDS="${LITELLM_MENU_STALL_TIMEOUT_SECONDS:-120}"
STREAM_START_TIMEOUT_SECONDS="${LITELLM_MENU_STREAM_START_TIMEOUT_SECONDS:-120}"
CODEX_COMPACTION_START_TIMEOUT_SECONDS="${LITELLM_MENU_CODEX_COMPACTION_START_TIMEOUT_SECONDS:-300}"
RECOVERY_MAX_SECONDS="${LITELLM_MENU_RECOVERY_MAX_SECONDS:-43200}"
RECOVERY_INTERVAL_SECONDS="${LITELLM_MENU_RECOVERY_INTERVAL_SECONDS:-5}"
WEB_FETCH_TIMEOUT_SECONDS="${LITELLM_MENU_WEB_FETCH_TIMEOUT_SECONDS:-30}"
WEB_SEARCH_MAX_RESULTS="${LITELLM_MENU_WEB_SEARCH_MAX_RESULTS:-8}"
WEB_SEARCH_READ_RESULTS="${LITELLM_MENU_WEB_SEARCH_READ_RESULTS:-4}"
WEB_SEARCH_READ_CHARS="${LITELLM_MENU_WEB_SEARCH_READ_CHARS:-1400}"
WEB_SEARCH_DDGS_BACKEND="${LITELLM_MENU_WEB_SEARCH_DDGS_BACKEND:-auto}"
WEB_SEARCH_REGION="${LITELLM_MENU_WEB_SEARCH_REGION:-us-en}"
WEB_SEARCH_MAX_ROUNDS="${LITELLM_MENU_WEB_SEARCH_MAX_ROUNDS:-6}"
WEB_SEARCH_MAX_QUERIES="${LITELLM_MENU_WEB_SEARCH_MAX_QUERIES:-16}"
WEB_SEARCH_MAX_OPEN_PAGES="${LITELLM_MENU_WEB_SEARCH_MAX_OPEN_PAGES:-8}"
WEB_SEARCH_MAX_FIND_IN_PAGE="${LITELLM_MENU_WEB_SEARCH_MAX_FIND_IN_PAGE:-12}"
EXTERNAL_WEB_SEARCH_MODEL_RETRIES="${LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRIES:-2}"
EXTERNAL_WEB_SEARCH_MODEL_RETRY_DELAY_SECONDS="${LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRY_DELAY_SECONDS:-1}"
IMAGE_TOOL_FALLBACK_MAX_ATTEMPTS="${LITELLM_MENU_IMAGE_TOOL_FALLBACK_MAX_ATTEMPTS:-3}"
DEPLOYMENT_COOLDOWN_FAILURES="${LITELLM_MENU_DEPLOYMENT_COOLDOWN_FAILURES:-2}"
DEPLOYMENT_COOLDOWN_SECONDS="${LITELLM_MENU_DEPLOYMENT_COOLDOWN_SECONDS:-300}"
COMPUTER_FACADE_BACKEND="${LITELLM_MENU_COMPUTER_FACADE_BACKEND:-auto}"
COMPUTER_FACADE_MODEL="${LITELLM_MENU_COMPUTER_FACADE_MODEL:-}"
COMPUTER_FACADE_MAX_STEPS="${LITELLM_MENU_COMPUTER_FACADE_MAX_STEPS:-20}"
COMPUTER_FACADE_TRACE="${LITELLM_MENU_COMPUTER_FACADE_TRACE:-0}"
COMPUTER_FACADE_TRACE_SCREENSHOTS="${LITELLM_MENU_COMPUTER_FACADE_TRACE_SCREENSHOTS:-0}"
COMPUTER_FACADE_ACTION_DENYLIST="${LITELLM_MENU_COMPUTER_FACADE_ACTION_DENYLIST:-}"
COMPUTER_FACADE_REQUIRE_OBSERVATION="${LITELLM_MENU_COMPUTER_FACADE_REQUIRE_OBSERVATION:-1}"
ROUTE_TRACE_PREVIEW_CHARS="${LITELLM_MENU_ROUTE_TRACE_PREVIEW_CHARS:-2000}"
LOCAL_MODEL_COST_MAP="${LITELLM_LOCAL_MODEL_COST_MAP:-True}"
PROXY_TELEMETRY="${LITELLM_PROXY_TELEMETRY:-False}"
DEFAULT_PORT="4000"
PORT="${LITELLM_PORT:-$DEFAULT_PORT}"
if [[ ! "$PORT" =~ ^[0-9]+$ ]] || (( PORT < 1 || PORT > 65535 )); then
  PORT="$DEFAULT_PORT"
fi
HOST="${LITELLM_HOST:-127.0.0.1}"
HEALTH_URL="http://127.0.0.1:$PORT/health/liveliness"
MODEL_INFO_URL="${LITELLM_MODEL_INFO_URL:-http://127.0.0.1:$PORT/model/info}"
MASTER_KEY="${LITELLM_MASTER_KEY:-sk-local-litellm}"
MODEL_INFO_FILE="${LITELLM_MODEL_INFO_FILE:-}"
PYTHON="${PYTHON:-}"
LITELLM_VERSION_FILE="${LITELLM_VERSION_FILE:-$TEMPLATE_ROOT/LITELLM_VERSION}"
BUNDLED_RUNTIME_DIR="${LITELLM_BUNDLED_RUNTIME_DIR:-$TEMPLATE_ROOT/runtime}"
DEFAULT_VENV_DIR="$ROOT/.venv"
if [[ -x "$BUNDLED_RUNTIME_DIR/bin/python" \
  && -x "$BUNDLED_RUNTIME_DIR/bin/litellm" \
  && -f "$BUNDLED_RUNTIME_DIR/LITELLM_VERSION" \
  && -f "$LITELLM_VERSION_FILE" ]] \
  && cmp -s "$BUNDLED_RUNTIME_DIR/LITELLM_VERSION" "$LITELLM_VERSION_FILE"; then
  DEFAULT_VENV_DIR="$BUNDLED_RUNTIME_DIR"
fi
VENV_DIR="${LITELLM_VENV_DIR:-$DEFAULT_VENV_DIR}"
NATIVE_PYTHON="${LITELLM_NATIVE_PYTHON:-$VENV_DIR/bin/python}"
LITELLM_BIN="${LITELLM_BIN:-$VENV_DIR/bin/litellm}"
NATIVE_PID_FILE="${LITELLM_NATIVE_PID_FILE:-$RUNTIME_DIR/litellm.pid}"
NATIVE_WORKERS="${LITELLM_NUM_WORKERS:-16}"
NATIVE_MAX_REQUESTS_BEFORE_RESTART="${LITELLM_MAX_REQUESTS_BEFORE_RESTART:-1000}"
BUNDLED_UV="${LITELLM_UV_BIN:-$TEMPLATE_ROOT/bin/uv}"
BUNDLED_PYTHON="${LITELLM_BUNDLED_PYTHON:-$TEMPLATE_ROOT/python/bin/python3}"
UV_PYTHON_INSTALL_DIR="${UV_PYTHON_INSTALL_DIR:-$ROOT/.uv-python}"
PYTHON_VERSION="${LITELLM_PYTHON_VERSION:-3.12}"
STATE_FILE="${LITELLM_STATE_FILE:-$ROOT/.litellm-runtime-state}"
STATE_TTL_SECONDS="${LITELLM_STATE_TTL_SECONDS:-180}"
HEALTH_WAIT_SECONDS="${LITELLM_HEALTH_WAIT_SECONDS:-60}"
RUNTIME_VERIFY_WAIT_SECONDS="${LITELLM_RUNTIME_VERIFY_WAIT_SECONDS:-30}"
SERVICE_LIFECYCLE_LOCK_DIR="${LITELLM_SERVICE_LIFECYCLE_LOCK_DIR:-$RUNTIME_DIR/service-lifecycle.lock}"
SERVICE_LIFECYCLE_LOCK_WAIT_SECONDS="${LITELLM_SERVICE_LIFECYCLE_LOCK_WAIT_SECONDS:-120}"
SERVICE_THROTTLE_INTERVAL_SECONDS="${LITELLM_SERVICE_THROTTLE_INTERVAL_SECONDS:-1}"
ROUTE_TRACE_STATE_FILE="${LITELLM_ROUTE_TRACE_STATE_FILE:-$RUNTIME_DIR/route-trace.enabled}"
ROUTE_TRACE_SCAN_LINES="${LITELLM_ROUTE_TRACE_SCAN_LINES:-5000}"
ROUTE_TRACE_LINES="${LITELLM_ROUTE_TRACE_LINES:-160}"
ROUTE_TRACE_MAX_REQUESTS="${LITELLM_ROUTE_TRACE_MAX_REQUESTS:-40}"
LAUNCHCTL_DOMAIN="gui/$(id -u)"
DEFAULT_LAUNCH_AGENT_LABEL="menu.litellm.service"
DEFAULT_APP_LAUNCH_AGENT_LABEL="menu.litellm.menu-login"
DEFAULT_CONFIG_WATCH_LABEL="menu.litellm.config-watch"
DEFAULT_APP_BUNDLE_PATH="/Applications/LiteLLM Menu.app"
DEFAULT_APP_RESOURCE_ROOT="$DEFAULT_APP_BUNDLE_PATH/Contents/Resources/App"
USER_DEFAULT_RUNTIME_ROOT="$HOME/.litellm-menu"
LAUNCH_AGENT_LABEL="${LITELLM_LAUNCH_AGENT_LABEL:-$DEFAULT_LAUNCH_AGENT_LABEL}"
SESSION_LAUNCH_AGENT_PLIST="${LITELLM_SESSION_LAUNCH_AGENT_PLIST:-$RUNTIME_DIR/$LAUNCH_AGENT_LABEL.plist}"
AUTOSTART_LAUNCH_AGENT_PLIST="${LITELLM_AUTOSTART_LAUNCH_AGENT_PLIST:-$HOME/Library/LaunchAgents/$LAUNCH_AGENT_LABEL.plist}"
LAUNCH_AGENT_PLIST="${LITELLM_LAUNCH_AGENT_PLIST:-$SESSION_LAUNCH_AGENT_PLIST}"
AUTOSTART_STATE_FILE="${LITELLM_AUTOSTART_STATE_FILE:-$RUNTIME_DIR/autostart.enabled}"
APP_LAUNCH_AGENT_LABEL="${LITELLM_APP_LAUNCH_AGENT_LABEL:-$DEFAULT_APP_LAUNCH_AGENT_LABEL}"
APP_LAUNCH_AGENT_PLIST="${LITELLM_APP_LAUNCH_AGENT_PLIST:-$HOME/Library/LaunchAgents/$APP_LAUNCH_AGENT_LABEL.plist}"
APP_BUNDLE_PATH="${LITELLM_APP_PATH:-}"
if [[ -z "$APP_BUNDLE_PATH" ]]; then
  if [[ "$TEMPLATE_ROOT" == */Contents/Resources/App ]]; then
    APP_BUNDLE_PATH="${TEMPLATE_ROOT%/Contents/Resources/App}"
  else
    APP_BUNDLE_PATH="$DEFAULT_APP_BUNDLE_PATH"
  fi
fi
export APP_BUNDLE_PATH
CONFIG_WATCH_LABEL="${LITELLM_CONFIG_WATCH_LABEL:-$DEFAULT_CONFIG_WATCH_LABEL}"
CONFIG_WATCH_PLIST="${LITELLM_CONFIG_WATCH_PLIST:-$HOME/Library/LaunchAgents/$CONFIG_WATCH_LABEL.plist}"
CONFIG_WATCH_LOG="${LITELLM_CONFIG_WATCH_LOG:-$ROOT/config-watch.log}"
CONFIG_WATCH_INTERVAL="${LITELLM_CONFIG_WATCH_INTERVAL:-5}"
CONFIG_WATCH_SETTLE_INTERVAL="${LITELLM_CONFIG_WATCH_SETTLE_INTERVAL:-2}"
WEBDAV_SYNC_SETTINGS="${LITELLM_WEBDAV_SYNC_SETTINGS:-$ROOT/webdav-sync.json}"
WEBDAV_SYNC_ENABLED_FILE="${LITELLM_WEBDAV_SYNC_ENABLED_FILE:-$RUNTIME_DIR/webdav-sync.enabled}"
WEBDAV_SYNC_STATUS_FILE="${LITELLM_WEBDAV_SYNC_STATUS_FILE:-$RUNTIME_DIR/webdav-sync-status.json}"
WEBDAV_SYNC_STATE_FILE="${LITELLM_WEBDAV_SYNC_STATE:-$RUNTIME_DIR/webdav-sync-state.json}"
WEBDAV_TIMEOUT="${LITELLM_WEBDAV_TIMEOUT:-30}"
