"""Bundled Runtime Settings schema used by the Python Core.

The React Native bundles deliberately exclude the legacy ``service/`` shell
backend.  Keep the display metadata and validation constraints in importable
Python data so Runtime Settings works identically in a portable Core bundle.
"""

from __future__ import annotations

from typing import Final


RUNTIME_SETTINGS_SCHEMA: Final[tuple[dict[str, object], ...]] = (
    {'key': 'LITELLM_MENU_REQUEST_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Request timeout', 'unit': 'seconds', 'kind': 'float', 'default': '7200', 'minimum': 0, 'maximum': 7200, 'help': 'Overall timeout for upstream model requests, continuation synthesis, and each recovery probe. 0 disables the local request cap.'},
    {'key': 'LITELLM_MENU_STREAM_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'First-event timeout', 'unit': 'seconds', 'kind': 'float', 'default': '120', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum wait for the first upstream stream event on ordinary requests. 0 falls back to Request timeout.'},
    {'key': 'LITELLM_MENU_CODEX_COMPACTION_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Compaction first-event', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum wait for the first event from a structured Codex compaction request. 0 falls back to Request timeout.'},
    {'key': 'LITELLM_MENU_STALL_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Stream idle timeout', 'unit': 'seconds', 'kind': 'float', 'default': '120', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum gap between stream events after the first event has arrived. 0 disables the local stream-idle cap.'},
    {'key': 'LITELLM_MENU_CODEX_DESCENDANT_CLEANUP', 'category': 'Recovery', 'label': 'Codex parent completion barrier', 'kind': 'bool', 'default': '1', 'help': 'Require a fresh full descendant snapshot before a root Codex task can end. Required implementation and test work is awaited; descendants that no longer affect the deliverable are interrupted deepest-first. Disable to use the native Codex lifecycle only.'},
    {'key': 'LITELLM_MENU_RECOVERY_MAX_SECONDS', 'category': 'Recovery', 'label': 'Recovery max', 'unit': 'seconds', 'kind': 'float', 'default': '14400', 'minimum': 0, 'maximum': 86400, 'help': 'Maximum route recovery polling time. The same connection stays alive with progress heartbeats while every route is cooling down, then retries after the first cooldown ends. 0 disables polling.'},
    {'key': 'LITELLM_MENU_RECOVERY_INTERVAL_SECONDS', 'category': 'Timeouts', 'label': 'Recovery interval', 'unit': 'seconds', 'kind': 'float', 'default': '5', 'minimum': 0.001, 'maximum': 3600, 'help': 'Delay between real route recovery probes.'},
    {'key': 'LITELLM_MENU_SAME_DEPLOYMENT_RETRIES', 'category': 'Recovery', 'label': 'Same-route retries', 'unit': 'retries', 'kind': 'int', 'default': '0', 'minimum': 0, 'maximum': 20, 'help': 'Additional attempts on the failed deployment before the next peer or order. Default 0 advances immediately; this also overrides LiteLLM Router retry-policy counts.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_BALANCE', 'category': 'Recovery', 'label': 'Balance / quota', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How insufficient balance, quota, or billing failures are handled.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_RATE_LIMIT', 'category': 'Recovery', 'label': 'Rate limit / overload', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How HTTP 429 and upstream overload or capacity failures are handled. Default recovery retries without cooling down the deployment.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_SERVER', 'category': 'Recovery', 'label': 'Server / gateway', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How temporary server failures, no healthy route, and gateway timeouts are handled.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_NETWORK', 'category': 'Recovery', 'label': 'Network', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How disconnects, DNS failures, and connection errors are handled. Default recovery does not cool down the deployment.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_STREAM_START_TIMEOUT', 'category': 'Recovery', 'label': 'First-event timeout', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How a local timeout before the first upstream stream event is handled.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_STREAM_IDLE_TIMEOUT', 'category': 'Recovery', 'label': 'Stream idle timeout', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How a local timeout after streaming has begun is handled. Default recovery does not cool down the deployment.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_REQUEST_ERROR', 'category': 'Recovery', 'label': 'Request / format error', 'kind': 'enum', 'default': 'error', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How deterministic request, format, model, policy, and context errors are handled. Default error returns a terminal failure so the proxy can be patched instead of waiting.'},
    {'key': 'LITELLM_MENU_WEB_FETCH_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Web fetch timeout', 'unit': 'seconds', 'kind': 'float', 'default': '12', 'minimum': 3, 'maximum': 60, 'help': 'Timeout for DDGS search and model-selected source-page fetches. This does not cap model generation.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_RESULTS', 'category': 'Web Search', 'label': 'Search results', 'unit': 'results', 'kind': 'int', 'default': '5', 'minimum': 1, 'maximum': 20, 'help': 'Maximum deduplicated DDGS results collected per search action across configured backends.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_READ_CHARS', 'category': 'Web Search', 'label': 'Readable page chars', 'unit': 'chars', 'kind': 'int', 'default': '1400', 'minimum': 200, 'maximum': 5000, 'help': 'Maximum extracted source-page characters returned after the model explicitly opens a result page. A model-directed page find scans up to 12000 characters to avoid false negatives.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_DDGS_BACKEND', 'category': 'Web Search', 'label': 'DDGS backend', 'kind': 'string', 'default': 'yahoo,bing', 'help': 'Comma-separated DDGS backends queried in order. The default tries Yahoo first, then Bing only when more results are needed; safe search is disabled.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_REGION', 'category': 'Web Search', 'label': 'Search region', 'kind': 'string', 'default': 'wt-wt', 'help': 'DDGS search region such as wt-wt, cn-zh, or us-en, passed directly to the DDGS SDK.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_ROUNDS', 'category': 'Web Search', 'label': 'Action rounds', 'unit': 'rounds', 'kind': 'int', 'default': '4', 'minimum': 1, 'maximum': 8, 'help': 'Maximum model-directed web-search action rounds for one response. Four rounds leave the model a turn to inspect a source found after changed queries.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_QUERIES', 'category': 'Web Search', 'label': 'Total queries', 'unit': 'queries', 'kind': 'int', 'default': '16', 'minimum': 1, 'maximum': 64, 'help': 'Maximum unique search queries across all web-search rounds.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_OPEN_PAGES', 'category': 'Web Search', 'label': 'Open pages', 'unit': 'pages', 'kind': 'int', 'default': '8', 'minimum': 0, 'maximum': 32, 'help': 'Maximum explicit page-open actions across all web-search rounds. 0 disables page opens.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_FIND_IN_PAGE', 'category': 'Web Search', 'label': 'Find in page', 'unit': 'actions', 'kind': 'int', 'default': '12', 'minimum': 0, 'maximum': 64, 'help': 'Maximum find-in-page actions across all web-search rounds. 0 disables in-page find.'},
    {'key': 'LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRIES', 'category': 'Web Search', 'label': 'Model retries', 'unit': 'retries', 'kind': 'int', 'default': '2', 'minimum': 0, 'maximum': 5, 'help': 'Retries for temporary rate-limit failures while the model plans or synthesizes bridged web search.'},
    {'key': 'LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRY_DELAY_SECONDS', 'category': 'Web Search', 'label': 'Model retry delay', 'unit': 'seconds', 'kind': 'float', 'default': '1', 'minimum': 0, 'maximum': 30, 'help': 'Base delay between temporary web-search model retries.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_BACKEND', 'category': 'Vision Bridge', 'label': 'Backend', 'kind': 'enum', 'default': 'auto', 'options': ['auto', 'local', 'api', 'off'], 'help': 'Auto tries the configured OpenAI-compatible endpoint first, then falls back to bundled local Vision OCR. Local skips any external vision endpoint. API requires a reachable OpenAI-compatible vision service. Off disables image-to-text fallback.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_API_BASE', 'category': 'Vision Bridge', 'label': 'API base', 'kind': 'string', 'default': 'http://127.0.0.1:11434/v1', 'help': 'OpenAI-compatible local vision endpoint, such as Ollama /v1 or another local API URL bridge.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_MODEL', 'category': 'Vision Bridge', 'label': 'Model', 'kind': 'string', 'default': 'qwen2.5vl:3b', 'help': 'Vision model used only to convert images into text before retrying the original route.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_API_KEY', 'category': 'Vision Bridge', 'label': 'API key', 'kind': 'string', 'default': '', 'secret': True, 'retain_existing': '__LITELLM_MENU_RETAIN_EXISTING__', 'help': 'Optional bearer token for the vision bridge endpoint. Leave unchanged to retain the saved token, or clear it to remove the token.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_TIMEOUT_SECONDS', 'category': 'Vision Bridge', 'label': 'Timeout', 'unit': 'seconds', 'kind': 'float', 'default': '45', 'minimum': 1, 'maximum': 600, 'help': 'Timeout for each local image-to-text bridge call.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_LOCAL_FORMAT', 'category': 'Vision Bridge', 'label': 'Local format', 'kind': 'enum', 'default': 'compact', 'options': ['compact', 'detailed'], 'help': 'Compact keeps local fallback summaries shorter to save tokens. Detailed includes the fuller region and element breakdown.'},
    {'key': 'LITELLM_MENU_VISION_BRIDGE_PROMPT', 'category': 'Vision Bridge', 'label': 'Prompt', 'kind': 'string', 'default': 'Describe the image accurately for a text-only language model. Include visible text, UI elements, layout, objects, and any important details.', 'help': 'Instruction sent to the local vision model when converting an image into text.'},
    {'key': 'LITELLM_MENU_UNKNOWN_MODEL_CONTEXT_WINDOW', 'category': 'Model Context', 'label': 'Unknown model raw context', 'unit': 'tokens', 'kind': 'int', 'default': '272000', 'minimum': 1, 'maximum': 16000000, 'help': 'Raw Codex context window used when no bundled, route, LiteLLM, or upstream metadata matches a model. 272000 displays about 258k at Codex’s 95% effective-window policy.'},
    {'key': 'LITELLM_MENU_MODEL_CONTEXT_REFRESH_HOURS', 'category': 'Model Context', 'label': 'Model context refresh', 'unit': 'hours', 'kind': 'int', 'default': '24', 'minimum': 0, 'maximum': 720, 'help': 'How often the managed Codex catalog refreshes public model-context metadata. 0 keeps the bundled and cached registry offline.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_FAILURES', 'category': 'Fallback', 'label': 'Cooldown failures', 'unit': 'failures', 'kind': 'int', 'default': '2', 'minimum': 0, 'maximum': 20, 'help': 'Consecutive upstream failures before that deployment/protocol pair is temporarily skipped. Other configured protocols on the same deployment remain eligible. 0 disables cooldown.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_SECONDS', 'category': 'Fallback', 'label': 'Cooldown duration', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 86400, 'help': 'How long a failed deployment/protocol pair is skipped after reaching the threshold. The deployment is excluded only while all configured protocols are cooling down. 0 disables cooldown.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_ORDINARY_ENABLED', 'category': 'Fallback', 'label': 'Ordinary requests write cooldown', 'kind': 'bool', 'default': '1', 'help': 'Whether failed ordinary requests add failures to the shared deployment cooldown pool. Existing cooldowns are still read by every request type.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_COMPACTION_ENABLED', 'category': 'Fallback', 'label': 'Compaction requests write cooldown', 'kind': 'bool', 'default': '0', 'help': 'Whether failed structured Codex compaction requests add failures to the shared deployment cooldown pool. Disabled by default so a compaction-specific upstream failure does not cool a route for ordinary work.'},
    {'key': 'LITELLM_MENU_IMAGE_TOOL_FALLBACK_MAX_ATTEMPTS', 'category': 'Fallback', 'label': 'Image tool attempts', 'unit': 'attempts', 'kind': 'int', 'default': '3', 'minimum': 0, 'maximum': 20, 'help': 'Maximum same-request image-generation tool recovery attempts before returning a safe failure. 0 disables this recovery.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_BACKEND', 'category': 'Computer Facade', 'label': 'Backend', 'kind': 'enum', 'default': 'auto', 'options': ['auto', 'mcp', 'browser', 'chrome', 'playwright', 'mock'], 'help': 'Executor backend. Explicit choices do not silently fall back to another real backend.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_MODEL', 'category': 'Computer Facade', 'label': 'Planner model', 'kind': 'string', 'default': '', 'help': 'Optional model group or route for the internal JSON planner. Empty uses the request model.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_MAX_STEPS', 'category': 'Computer Facade', 'label': 'Max steps', 'unit': 'steps', 'kind': 'int', 'default': '20', 'minimum': 1, 'maximum': 200, 'help': 'Maximum computer observation/action turns before safe failure.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_TRACE', 'category': 'Computer Facade', 'label': 'Trace', 'kind': 'bool', 'default': '0', 'help': 'Log action summaries and backend choices to route trace.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_TRACE_SCREENSHOTS', 'category': 'Computer Facade', 'label': 'Trace screenshots', 'kind': 'bool', 'default': '0', 'help': 'Privacy-sensitive: when enabled, screenshots are written locally with 0600 permissions instead of being logged inline.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_ACTION_DENYLIST', 'category': 'Computer Facade', 'label': 'Action denylist', 'kind': 'string', 'default': '', 'help': 'Comma-separated actions to block, for example click,type,drag.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_REQUIRE_OBSERVATION', 'category': 'Computer Facade', 'label': 'Require observation', 'kind': 'bool', 'default': '1', 'help': 'Require executor observation before planner completion or action success.'},
    {'key': 'LITELLM_MENU_LOG_MAX_BYTES', 'category': 'Logs', 'label': 'Local log file cap', 'unit': 'MB', 'kind': 'mb', 'default': '10', 'minimum': 0.25, 'maximum': 100, 'help': 'Per-file cap for local logs: recent requests, service stdout/stderr, and menu actions. Each log keeps one .1 backup containing the previous tail.'},
    {'key': 'LITELLM_MENU_LOG_VIEW_LIMIT', 'category': 'Logs', 'label': 'Log view rows', 'unit': 'rows', 'kind': 'int', 'default': '10000', 'minimum': 100, 'maximum': 100000, 'help': 'Maximum rows shown per log tab. This changes the view only and does not delete local log data.'},
    {'key': 'LITELLM_MENU_ROUTE_TRACE_PREVIEW_CHARS', 'category': 'Logs', 'label': 'Trace preview chars', 'unit': 'chars', 'kind': 'int', 'default': '2000', 'minimum': 80, 'maximum': 2000, 'help': 'Maximum request-preview characters retained in the always-on local route trace.'},
    {'key': 'LITELLM_USE_SYSTEM_PROXIES', 'category': 'Network', 'label': 'Use system proxies', 'kind': 'bool', 'default': '0', 'help': 'Allow upstream HTTP clients to use macOS system proxy settings. Off isolates LiteLLM from system proxy auto-discovery.'},
    {'key': 'LITELLM_PORT', 'category': 'Service', 'label': 'Local port', 'kind': 'int', 'default': '4000', 'minimum': 1, 'maximum': 65535, 'help': 'Local HTTP port for the LiteLLM proxy. Changing this updates health checks and requires a service restart.'},
    {'key': 'LITELLM_NUM_WORKERS', 'category': 'Service', 'label': 'Worker count', 'unit': 'workers', 'kind': 'int', 'default': '16', 'minimum': 1, 'maximum': 64, 'help': 'LiteLLM Menu runs 16 Uvicorn workers by default. Keep this value at 16 unless the user explicitly changes the service concurrency setting.'},
    {'key': 'LITELLM_MAX_REQUESTS_BEFORE_RESTART', 'category': 'Service', 'label': 'Worker request recycle', 'unit': 'requests', 'kind': 'int', 'default': '1000', 'minimum': 1, 'maximum': 100000, 'help': 'Restart each Gunicorn worker after this many handled requests to cap long-running memory growth.'},
    {'key': 'LITELLM_STATE_TTL_SECONDS', 'category': 'Service', 'label': 'State TTL', 'unit': 'seconds', 'kind': 'int', 'default': '180', 'minimum': 1, 'maximum': 3600, 'help': 'How long transient start/stop state is considered fresh.'},
    {'key': 'LITELLM_HEALTH_WAIT_SECONDS', 'category': 'Service', 'label': 'Health wait', 'unit': 'seconds', 'kind': 'int', 'default': '60', 'minimum': 1, 'maximum': 600, 'help': 'How long start/restart waits for the health endpoint.'},
    {'key': 'LITELLM_RUNTIME_VERIFY_WAIT_SECONDS', 'category': 'Service', 'label': 'Runtime verify wait', 'unit': 'seconds', 'kind': 'int', 'default': '30', 'minimum': 1, 'maximum': 600, 'help': 'How long runtime config verification may wait.'},
    {'key': 'LITELLM_SERVICE_LIFECYCLE_LOCK_WAIT_SECONDS', 'category': 'Service', 'label': 'Lifecycle lock wait', 'unit': 'seconds', 'kind': 'int', 'default': '120', 'minimum': 1, 'maximum': 1800, 'help': 'Maximum wait for concurrent start/restart/apply-config operations.'},
)


def runtime_settings_metadata() -> list[dict[str, object]]:
    """Return a defensive copy for UI projection and validation."""

    return [dict(item) for item in RUNTIME_SETTINGS_SCHEMA]
